spring:
  application:
    name: freshly-backend

  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java,src/main/resources
      poll-interval: 2s
      quiet-period: 1s
      exclude: static/**,public/**
    livereload:
      enabled: true

  docker:
    compose:
      enabled: false

  mongodb:
    host: localhost
    port: 27017
    database: freshly_db
    username: root
    password: root
    authentication-database: admin
    representation:
      uuid: STANDARD

  mail:
    host: localhost
    port: 1025
    username: vertyll
    password: vertyll
    from: no-reply@freshly.local
    properties:
      mail:
        smtp:
          trust: "*"
          auth: false
          starttls:
            enable: false
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000/realms/freshly
          jwk-set-uri: http://localhost:9000/realms/freshly/protocol/openid-connect/certs

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

security:
  jwt:
    secret: isN5Z1EinzeD2JyjXq6SZqoBd+QpOJMxZsBHwfhXHAA=
    expiration:
      email-verification: 86400000
      password-reset: 3600000
    refresh-token:
      expiration: 1800000
      cookie-name: KEYCLOAK_REFRESH_TOKEN
    cookie:
      httpOnly: true
      secure: false
      sameSite: Strict
      path: "/"

external-service:
  gios:
    api-url: https://api.gios.gov.pl/pjp-api/v1/rest

application:
  file:
    uploads:
      file-output-path: ./uploads

  frontend:
    url: http://localhost:4200

  keycloak:
    server-url: http://localhost:9000
    realm: freshly
    admin-client-id: freshly-service-account
    admin-client-secret: IEKlEpXPeu0Cd0SjUzEPImaIz8NDougC
    user-client-id: freshly-app-client
    user-client-secret: YTJcSSBrtEuC2VoNFlGbNVVMPtqokEC8
    roles-claim-path: roles

server:
  port: 8080

logging:
  level:
    root: INFO
    com.vertyll.freshly: DEBUG
    org.springframework.security: DEBUG
    org.springframework.mail: DEBUG